sudo: required

services:
 - docker

before_install:
 - docker build -t bk20191210/frontend -f Dockerfile.dev .

script:
 - docker run -e CI=true bk20191210/frontend npm run test

deploy:
 provider: openshift
 user: $OPENSHIFT_USER_ID
 password: $OPENSHIFT_PASSWD
 domain: $OPENSHIFT_PROJECT
 app: frontend

