sudo: required

services:
 - docker

before_install:
 - docker build -t bk20191210/frontend -f Dockerfile.dev .

script:
 - docker run -e CI=true bk20191210/frontend npm run test

deploy:
 provider: openshift
 server: $OPENSHIFT_SERVER
 token: $OPENSHIFT_TOKEN
 project: $OPENSHIFT_PROJECT
 on:
  branch: master
 edge: true
